baseURL = 'https://th3-j0k3r.github.io/th3-j0k3r.github.io/'
languageCode = 'en-us'
title = 'Akhil Mahendra'
theme = "hugo-blog-awesome"


[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.

  [[menu.main]]
    pageRef="blog"
    name = 'blog'
    url = '/blog/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    pageRef="notes"
    name = 'Notes'
    url = '/notes/'
    weight = 30
   [[menu.main]]
    pageRef="usersthis"
    name = 'Uses this'
    url = '/usesthis/usesthis/'
    weight = 30
   [[menu.main]]
    pageRef="books"
    name = 'books'
    url = 'https://www.goodreads.com/user/show/148803922-akhil-mahendra'
    weight = 40

googleAnalytics = '' # G-MEASUREMENT_ID




[[params.socialIcons]]
name = "github"
url = "https://github.com/th3-j0k3r"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Akhil_Mahendra"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/akhil-mahendra/"